# Generated by Django 3.1.4 on 2020-12-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botson', '0003_auto_20201225_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadup',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='stadup',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пользователь'),
        ),
    ]
