# Generated by Django 3.1.4 on 2020-12-25 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botson', '0004_auto_20201225_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadup',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='stadup',
            name='first_answer',
        ),
        migrations.RemoveField(
            model_name='stadup',
            name='second_answer',
        ),
        migrations.RemoveField(
            model_name='stadup',
            name='third_answer',
        ),
        migrations.AddField(
            model_name='stadup',
            name='done',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stadup',
            name='problems',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stadup',
            name='publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadup',
            name='todo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stadup',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
