# Generated by Django 3.1.4 on 2021-01-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botson', '0005_auto_20201225_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadup',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
